[build]
builder = "nixpacks"
buildCommand = "cd gestion-pharmacie && apt-get update && apt-get install -y openjdk-21-jdk && export JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64 && chmod +x mvnw && ./mvnw clean package -DskipTests"

[deploy]
startCommand = "cd gestion-pharmacie && java -jar target/gestion-pharmacie-0.0.1-SNAPSHOT.jar"

[deploy.env]
JAVA_VERSION = "21"
SPRING_DATASOURCE_URL = "jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
SPRING_DATASOURCE_USERNAME = "${MYSQLUSER}"
SPRING_DATASOURCE_PASSWORD = "${MYSQLPASSWORD}"
JWT_SECRET = "votreCleSecreteTresLongueEtComplexePourLaProduction"
