[build]
builder = "java"
buildCommand = "cd gestion-pharmacie && ./mvnw clean package -DskipTests"

[deploy]
startCommand = "cd gestion-pharmacie && java -jar target/gestion-pharmacie-0.0.1-SNAPSHOT.jar"
healthcheckPath = "/api/health"
healthcheckTimeout = 100

[deploy.env]
JAVA_VERSION = "21" 