[build]
builder = "nixpacks"
buildCommand = "cd gestion-pharmacie && ./mvnw clean package -DskipTests"

[deploy]
startCommand = "java -jar gestion-pharmacie/target/gestion-pharmacie-0.0.1-SNAPSHOT.jar"

[deploy.env]
JAVA_VERSION = "21"
