name: Backend CD

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'gestion-pharmacie/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Railway login & deploy
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          echo $RAILWAY_TOKEN | railway login
          railway up --service backend
