name: Backend CD

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'gestion-pharmacie/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Deploy to Railway
        uses: bervProject/railway-deploy@v1.0.0
        with:
          token: ${{ secrets.RAILWAY_TOKEN }}
          service: backend
