name: Backend CD

on:
  workflow_run:
    workflows: ["Backend CI"]
    branches: [main]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: |
          cd gestion-pharmacie
          mvn clean package -DskipTests

      - name: Install Railway CLI
        run: npm i -g @railway/cli

      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          SPRING_DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL }}
          SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: |
          cd gestion-pharmacie
          echo $RAILWAY_TOKEN | railway login
          railway link
          railway variables set \
            SPRING_DATASOURCE_URL="$SPRING_DATASOURCE_URL" \
            SPRING_DATASOURCE_USERNAME="$SPRING_DATASOURCE_USERNAME" \
            SPRING_DATASOURCE_PASSWORD="$SPRING_DATASOURCE_PASSWORD" \
            JWT_SECRET="$JWT_SECRET"
          railway up --service backend 