name: Backend CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'gestion-pharmacie/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'gestion-pharmacie/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: |
        cd gestion-pharmacie
        mvn clean install -DskipTests
    
    - name: Run Tests
      run: |
        cd gestion-pharmacie
        mvn test
      env:
        SPRING_PROFILES_ACTIVE: test
        SPRING_DATASOURCE_URL: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=MySQL
        SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.h2.Driver
        SPRING_DATASOURCE_USERNAME: sa
        SPRING_DATASOURCE_PASSWORD: 
        JWT_SECRET: testSecretKey123456789testSecretKey123456789testSecretKey123456789
        JWT_EXPIRATION: 86400000
    
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: gestion-pharmacie/target/surefire-reports/