name: Backend CD

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'gestion-pharmacie/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Install Railway CLI
        run: npm i -g @railway/cli

      - name: Railway login & deploy
        env:
          RAILWAY_TOKEN: 4c94f2f0-b018-4fc3-beae-759c16ac44c7
        run: |
          railway login --token $RAILWAY_TOKEN
          railway up --service backend
