name: Backend CD

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'gestion-pharmacie/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Install Railway CLI
        run: npm i -g @railway/cli

      - name: Create Railway config directory
        run: mkdir -p ~/.railway

      - name: Set Railway token for login
        run: echo ${{ secrets.RAILWAY_TOKEN }} > ~/.railway/config.json

      - name: Deploy to Railway
        run: railway up --service backend
